### ISSUE TITLE
Publish v5.0.0 version to pypi

### ISSUE THREAD

**Issue by SeanGol** [lk-geimfari/mimesis#1096]
# Release request

## Version Info

- version: 5.0.0

## Expected

- Version 5.0.0 appears in [mimesis release history](https://pypi.org/project/mimesis/#history) of pypi

**Comment by lk-geimfari** [comment]
I'm still working on it and it contains truly a lot of changes (including major changes).

Mimesis 5.0.0 will require Python 3.8^.

I'll release It in a month, I think.

**Comment by jodiekurnia** [comment]
hi, if releasing v5.0.0 on pypi will delayed by a month, can we just access documentation for v4.1.3?
since docs are for v5.0.0 and installation guide make us install older version (v4.1.3) and as you said it has a lot of changes, so v5.0.0 documentation while we can only install v4.1.3 via pip install mimesis is doesn’t makes any sense.

**Comment by lk-geimfari** [comment]
@jodiekurnia The documentations of 5.0.0 is mostly applicable to 4.1.3 too.

**Comment by lk-geimfari** [comment]
I'm closing this issue since I've published 4.1.3 docs on https://mimesis.name.
