### ISSUE TITLE
Implementing custom provider for factory_boy.

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#244]
This issue is based on suggestion of @sobolevn from issue #199.

Quote:
```
I came with even better idea: why now implementing custom provider for factory_boy?
It already has all the stuff we need!
```

If you want to take solve this issue, please read #199.

**Comment by SteadBytes** [comment]
Would this be something similar to the [faker module](http://factoryboy.readthedocs.io/en/latest/_modules/factory/faker.html) - `factory.faker`  for factory_boy? I've read #199 but am still a bit unsure.

**Comment by sobolevn** [comment]
That was my original idea.

**Comment by SteadBytes** [comment]
Aha ok thank you 👍  , `factory.faker` is part of factory_boy, so this would be PR to factory_boy? Otherwise we'd need to pull in factory_boy as a dependency and add the functionality here - which would go against the claim in 
 mimesis README that no other modules are required. Or am I missing something?  I'd love to have a go at this but I don't want to get it wrong! 😕

**Comment by lk-geimfari** [comment]
@sobolevn What do you suggest?
Something like this?
```python
try:
    from module import something
except ImportError:
    raise ImportError("You should install factory_boy for using this feature")
```

or maybe just PR to factory_boy?

**Comment by lk-geimfari** [comment]
Also i have created this[ issue](https://github.com/FactoryBoy/factory_boy/issues/423) in the repository of factory_boy.
