### ISSUE TITLE
Add pytest-randomly 

### ISSUE THREAD

**Issue by sobolevn** [lk-geimfari/mimesis#468]
We need to run tests in random order to be sure, that they do not depend on each other.

https://github.com/pytest-dev/pytest-randomly

**Comment by lk-geimfari** [comment]
@sobolevn Seems like this already fixed.

**Comment by sobolevn** [comment]
No, it is not fixed. https://github.com/pytest-dev/pytest-randomly/issues/135

**Comment by lk-geimfari** [comment]
So, we can implement it now: https://github.com/pytest-dev/pytest-randomly/pull/187

**Comment by lk-geimfari** [comment]
@sobolevn Do you know how to add entry point to mimesis? I'm not sure that I completely understand the idea of how `pytest-randomly` works with entry points.

**Comment by sobolevn** [comment]
Nope, sorry, I haven't seen it yet.

**Comment by tabassco** [comment]
If no one is working on this at the moment, I'd like to give it a shot.

**Comment by tabassco** [comment]
Checking this issue vs #469 I see it that this issue is already fulfilled. As described in the opening post, the intent was to run pytest in random order to check for possible dependencies of the tests. 

To make use of the seed functionality in pytest-randomly I modified the makefile so that it now takes an optional parameter SEED. 

```
SEED = unspecified

ifeq ("$(SEED)", "unspecified")
RANDOM_SEED =
else
RANDOM_SEED = --randomly-seed=$(SEED)
endif
```

```
.PHONY: test
test:
	pytest --color=yes $(RANDOM_SEED) ./
	mypy mimesis/ tests/
	make clean
```


SEED can be:
 "last" -> rerunning the tests with the seed from the previous run
  int -> giving specific seed

As I'm mainly a Python developer I'm not that well versed in makefiles and would appreciate your modifications in making it prettier.
