### ISSUE TITLE
Support pytest-randomly

### ISSUE THREAD

**Issue by sobolevn** [lk-geimfari/mimesis#469]
It is said, that `pytest-randomly` supports `faker` and `factory-boy`:

```
Randomly shuffles the order of test items. This is done first at the level of modules, then at the level of test classes (if you have them), then at the order of functions. This also works with things like doctests.
Resets random.seed() at the start of every test case and test to a fixed number - this defaults to time.time() from the start of your test run, but you can pass in --randomly-seed to repeat a randomness-induced failure.
If factory boy is installed, its random state is reset at the start of every test. This allows for repeatable use of its random 'fuzzy' features.
If faker is installed, its random state is reset at the start of every test. This is also for repeatable fuzzy data in tests - factory boy uses faker for lots of data.
If numpy is installed, its random state is reset at the start of every test.
```

We need to think about possible integration with this project.

**Comment by sobolevn** [comment]
@lk-geimfari friendly ping. Do you have some time to work on this? https://github.com/pytest-dev/pytest-randomly/issues/135

**Comment by lk-geimfari** [comment]
@sobolevn I'm sorry, but I really can't work on any issue at this weekends. I'll try to work on it in next weekends.

**Comment by lk-geimfari** [comment]
@sobolevn Can you, please, tell me what steps exactly should I do?

**Comment by sobolevn** [comment]
It is better to ask `pytest-randomly` maintainers. I don't remember what is the status of this issue.

**Comment by lk-geimfari** [comment]
@sobolevn I hear ya. Already done! Thanks!

**Comment by lk-geimfari** [comment]
Fixed in #849

**Comment by MKaras93** [comment]
Hello, I have a question - is randomly supported on 4.1.3? I'm working on Python 3.6, so I can't install a newer version. I'm using `mimesis==4.1.3` and `pytest-randomly==3.10.3`, however even with argument `--randomly-seed=1` I'm getting different results from mimesis when I rerun test. Other random tools repeat their output as expected, I only have problem with mimesis.

It's possible that the problem is on my side (there are some custom factories which I haven't written, I'm still figuring it out), but it would definitely help to know if mimesis seed can be controlled by randomly in 4.1.3.

I've tried to figure it out from the commit list, but there are quite a few issues mentioning this problem and I'm not sure if they refer to the same thing.

**Comment by sobolevn** [comment]
I have a PR ready ;)

**Comment by sobolevn** [comment]
Fixed by https://github.com/lk-geimfari/mimesis/pull/1325
