### ISSUE TITLE
PyPi auto deployment fails

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#763]
I've tried to publish v3.4.0, but it seems something is wrong.

More details here: https://travis-ci.org/lk-geimfari/mimesis/jobs/615995403

**Comment by lk-geimfari** [comment]
@jwilges @ceccoemi Any ideas of how we can fix it?

**Comment by jwilges** [comment]
Hey @lk-geimfari, I can try to take a look. I am not at a computer at the moment but after looking at the log and a quick glance through the Travis documentation I think it might be worth trying this first since it’s easy to check:

Edit the `deploy` section of the Travis config file to have this: `skip_existing: true`.

I haven’t used Travis CI prior to looking at this project (I have been using CircleCI which is similar but lacks this fancy built in pypi deploy step) so to really look into solving this I will have to setup Travis on my fork of the project to test it against the test PyPI server so I can reproduce the issue and look into a fix, then I should be able to submit that as a pull request here.

The log makes it look like existing build artifacts are perhaps conflicting, but I noticed your deploy condition tries to select only one (Linux Python 3.6) build, so it’s unexpected behavior. The `skip_existing` setting might let us work around it in the short term if we are lucky. But if that fails, I’ll have to look at it properly in a fork with some trial and error.

**Comment by lk-geimfari** [comment]
@jwilges Unfortunately, it [did not help](https://travis-ci.org/lk-geimfari/mimesis/jobs/616106977).

**Comment by jwilges** [comment]
Thanks for checking - that was my only quick guess without looking into it deeply. The log output was not incredibly enlightening, for some reason. I'll see if I can set aside some time to reproduce the deploy issue in my fork of the project so we can get new releases going again.

**Comment by lk-geimfari** [comment]
UPD: I think that in this version has no enough to be 3.4.0, so I guess it will be 3.3.1, when we solve the problem with deployment.

**Comment by lk-geimfari** [comment]
@ceccoemi If you have free time to contribute, please look at this issue too. Thank you!

**Comment by ceccoemi** [comment]
@lk-geimfari  it's a bit difficult to reproduce for me.

Have you seen [this](https://travis-ci.community/t/unable-to-upload-package-to-pypi/5260)? They resolved it by escaping special characters in the password.

**Comment by lk-geimfari** [comment]
@ceccoemi I remembered now that a month ago I have changed the password of my PyPi account and absolutely forget about changing it in Travis CI environment variables. I think that this issue is not actual anymore and I'll close it as soon as I release 3.3.1.

**Comment by lk-geimfari** [comment]
@ceccoemi I'll wait for your changes related to `Number` providers and then — I'll create a release.

**Comment by lk-geimfari** [comment]
I think there is no need to keep it opened.
